### ISSUE TITLE
Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by oYo-fr** [DeviantJS/angular2-seed-material2#10]
Before submitting the issue, take a look at the already existing solutions to:

- [x] `Cannot find module '...'` - your issue is related to not existing type definitions.
- [x] Adding [sass support](https://github.com/mgechev/angular2-seed/wiki/Add-custom-Gulp-task).
- [x] Adding [external styles](https://github.com/mgechev/angular2-seed/wiki/Add-an-external-styles).
- [x] Configuring [SystemJS](https://github.com/mgechev/angular2-seed/issues/499).
- If you are not sure your configuration is correct, please take a look at the documentation of [SystemJS](https://github.com/systemjs/systemjs/blob/master/docs/system-api.md), [typings](https://github.com/typings/typings/blob/master/README.md) and [gulp](https://github.com/gulpjs/gulp/blob/master/docs/README.md).

**Comment by oYo-fr** [comment]
I get this error within the browser console after npm start.
I instaled latest npm & node version.
I also instaled ts-node...
Does anyone gets the same error ?

**Comment by oYo-fr** [comment]
core.js?1458576243023:5Uncaught ReferenceError: require is not defined
button.js?1458576243024:15Uncaught ReferenceError: require is not defined
card.js:10 Uncaught ReferenceError: require is not defined
checkbox.js:10 Uncaught ReferenceError: require is not defined
progress-circle.js:15 Uncaught ReferenceError: require is not defined
sidenav.js?1458576243026:18Uncaught ReferenceError: require is not defined
toolbar.js:10 Uncaught ReferenceError: require is not defined

**Comment by d3viant0ne** [comment]
@oYo-fr ts-node is included in the seed this is based off of.

Give me a few minutes to pick up the latest changes from master and i'll take a look

**Comment by oYo-fr** [comment]
ok thanks, let me know if you are able to reproduce that problem :)

**Comment by d3viant0ne** [comment]
For reference what it's looking for is 

```
// RTL
__export(require('./rtl/dir'));
```
Which is exported in @angular2-matrial/core

As to why it isn't picking it up, i'm not quire sure but I'm going to assume the answer is going to be "alpha"

**Comment by d3viant0ne** [comment]
Also something to note, the source maps in their published packages are incorrect which will also cause issues.

**Comment by oYo-fr** [comment]
Is there any quick fix ?

**Comment by d3viant0ne** [comment]
For reference, it doesn't prevent you from using material2

![screen shot 2016-03-21 at 12 56 41 pm](https://cloud.githubusercontent.com/assets/8420490/13928603/608dc610-ef64-11e5-88e1-f32306f4349f.png)

**Comment by d3viant0ne** [comment]
That undefined reference is related to right side "whatever" i.e. right side navigation

**Comment by oYo-fr** [comment]
To be honest, I have no idea what this error means, and what it does not allow me to do... So it's not "that" bad ?

**Comment by d3viant0ne** [comment]
It will only prevent you from something like a right side navigation drawer

**Comment by oYo-fr** [comment]
That's good to know. Thank you for taking the time to watch this problem :)

**Comment by d3viant0ne** [comment]
No problem. Once Angular2 Beta.12 is tagged this week, i'll be updating all the visual components to use  Material2

**Comment by d3viant0ne** [comment]
Also worth noting, if you want to play around with Material2 without all the extra complexity of the seed for the time being, i'd go take a look at this ...

https://github.com/jelbourn/material2-app

**Comment by oYo-fr** [comment]
Thank you very much for that link, that is exactly what I was looking for :)

**Comment by andvasp** [comment]
Hi Guys,

I noticed the same problem. After a lot of trys, I solved the problem removing the packageConfigPaths and the additional_deps in project.config.ts. I also added the material packages as shown below. It runs without error but I don't know the impact to the seed project. Can I do like I did? The Production build will be generated?

System.config({
"defaultJSExtensions": true,
_**"packageConfigPaths": [
"/node_modules/*/package.json",
]**_

System.config({
  "defaultJSExtensions": true,
  "paths": {
    "main": "/main",
    "angular2/*": "/angular2/*",
    "rxjs/*": "/rxjs/*",
    "app/*": "/app/*",
    "*": "/node_modules/*"
  },
  "packages": {
    "angular2": {
      "defaultExtension": false
    },
    "rxjs": {
      "defaultExtension": false
    },
    "@angular2-material/core": {
      "format": "cjs", "defaultExtension": "js", "main": "core.js"
    },
    "@angular2-material/components": {
      "format": "cjs", "defaultExtension": "js"
    },
    "@angular2-material/checkbox": {
      "format": "cjs", "defaultExtension": "js", "main": "checkbox.js"
    },
    "@angular2-material/button": {
      "format": "cjs", "defaultExtension": "js", "main": "button.js"
    },
    "@angular2-material/toolbar": {
      "format": "cjs", "defaultExtension": "js", "main": "toolbar.js"
    },
    "@angular2-material/sidenav": {
      "format": "cjs", "defaultExtension": "js", "main": "sidenav.js"
    },
    "@angular2-material/list": {
      "format": "cjs", "defaultExtension": "js", "main": "list.js"
    },
    "@angular2-material/input": {
      "format": "cjs", "defaultExtension": "js", "main": "input.js"
    }
  }
})

**Comment by d3viant0ne** [comment]
@andvasp - After digging into that error again, here is my take on the whole thing.

- The key takeaway from all of it is that the reference error only prevents "right side component" functionality which imo isn't a feature I want to go chasing errors for. 

Also, while what you suggested "works" it's not the way it "should" work and negates the extensibility of the seed by stripping out the ability to add additional dependencies to the project.config.

Given the alpha nature of Material2 & the still very beta nature of Angular2 / systemjs, this just isn't the time to go chasing errors that will eventually be resolved as these products mature.
