### ISSUE TITLE
Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by Panthro** [DeviantJS/angular2-seed-material2#20]
Just cloned master

`npm install`

`npm start`

Open on Chrome and:
<img width="1437" alt="screen shot 2016-04-26 at 15 56 20" src="https://cloud.githubusercontent.com/assets/1565421/14820561/76e1e3fe-0bc7-11e6-8870-5955d2e23102.png">

**Comment by d3viant0ne** [comment]
https://github.com/DeviantJS/angular2-seed-material2/issues/10

**Comment by Panthro** [comment]
well, maybe add something to the readme? still not clear to me how to solve the issue...

**Comment by d3viant0ne** [comment]
The issues isn't something to be resolved right now. Material2 is an early alpha and the issues ins't blocking
