### ISSUE TITLE
material2 styles loaded twice

### ISSUE THREAD

**Issue by DanPii** [DeviantJS/angular2-seed-material2#21]
Hi,
this might be more a question than a bug, because i'am still new to angular2.

i just cloned the master and noticed that the styles of material2 components (button, input, card, etc.) are loaded twice in` <head>`.
Once the injected file which is setup in project.config.ts ( `{ src: '@angular2-material/button/button.css', inject: true },` ) and once by angular2, which loads component css as inline `<style>`.

![material2 styles loaded twice](https://cloud.githubusercontent.com/assets/16837118/14870940/382b41c4-0cde-11e6-83c3-1ee20b2cd8cf.png)

If i make some changes in main.css, e.g. changing the font-family:
`body {  font-family: "Open Sans";}`, 
these changes are overwritten by the material2 components (button, input, card, etc.) 
![material2 styles loaded twice 2](https://cloud.githubusercontent.com/assets/16837118/14870955/6892cb34-0cde-11e6-9449-c22e692f5ca9.png)

Is this behaviour expected? If so, i would have to overwrite the font-familiy for every single material2 component i use.
Or is there a way to load / inject the main.css file at the end?

Thanks in advance,
Daniel

**Comment by d3viant0ne** [comment]
Good catch, I hadn't noticed that. I'll take a look at it shortly, thought I can tell you it certainly isn't expected or desirable. As to weather or not it's fixable or not right now is another question entirely.

**Comment by d3viant0ne** [comment]
Issue resolved with #26
