### ISSUE TITLE
app not starting due to missing `@angular/core` dependency

### ISSUE THREAD

**Issue by j1fig** [DeviantJS/angular2-seed-material2#23]
**Steps to reproduce and a minimal demo of the problem**

Cloned the project, `npm install`ed yields warning:

`npm WARN @angular2-material/core@2.0.0-alpha.4 requires a peer of @angular/common@^2.0.0-rc.0 but none was installed.`

Indeed, running `npm start` afterwards yields:

`.../angular2-seed-material2/node_modules/@angular2-material/input/input.d.ts(2,38): error TS2307: Cannot find module '@angular/common'.`

Should I add `@angular/core` to packages.json? Which version? Will it conflict with `"angular2": "2.0.0-beta.17`?

**Comment by d3viant0ne** [comment]
Issue resolved with #26
