### ISSUE TITLE
 Error on fetch for @angular2-material

### ISSUE THREAD

**Issue by marianzburlea** [DeviantJS/angular2-seed-material2#28]
**build the project**

**Current behavior**
Error on fetch for @angular2-material/card/card.js at file:///var/www/test/angular2-seed-material2/node_modules/@angular2-material/card/card.js
        Loading dist/tmp/app/+about/about.component.js
        Loading dist/tmp/app/+about/index.js
        Loading dist/tmp/app/app.component.js
        Loading dist/tmp/app/main.js
        Error: ENOENT: no such file or directory, open '/var/www/test/angular2-seed-material2/node_modules/@angular2-material/card/usr/local/google/home/jelbourn/material2/tmp/broccoli_type_script_compiler-input_base_path-IydvmmBU.tmp/0/components/card/card.js.map'
    at Error (native)
[08:48:13] 'build.prod' errored after 15 s
[08:48:13] Error in plugin 'run-sequence(build.bundles.app)'
Message:
    build.bundles.app callback

**Expected/desired behavior**
build successfully

**Other information**
I've tried on Windows 10 and Ubuntu 14. Both have the same error.

**Comment by d3viant0ne** [comment]
angular/material2#541
