### ISSUE TITLE
Sidenav isn't functioning for me.

### ISSUE THREAD

**Issue by mikepc** [DeviantJS/angular2-seed-material2#31]
**IMPORTANT**: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here.

**Steps to reproduce and a minimal demo of the problem**
Click the 3 dots in the upper-right corner

_What steps should we try in your demo to see the problem?_
Click the menu button in the upper-right corner

**Current behavior**
No navigation appears.

**Expected/desired behavior**
Navigation appears.

**Other information**
    "@angular/common": "2.0.0-rc.1",
    "@angular/compiler": "2.0.0-rc.1",
    "@angular/core": "2.0.0-rc.1",
    "@angular/http": "2.0.0-rc.1",
    "@angular/platform-browser": "2.0.0-rc.1",
    "@angular/platform-browser-dynamic": "2.0.0-rc.1",
    "@angular/router": "2.0.0-rc.1",
    "es6-module-loader": "^0.17.8",
    "core-js": "^2.4.0",
    "rxjs": "5.0.0-beta.6",
    "systemjs": "0.19.26",
    "zone.js": "^0.6.12"

Cloned master on 6/14/2016

**Comment by d3viant0ne** [comment]
There is no "sidenav" component built

**Comment by mikepc** [comment]
<sd-toolbar></sd-toolbar>
<sd-navbar></sd-navbar>
<router-outlet></router-outlet>
