### ISSUE TITLE
Update to 2.0.0-rc.3 with router 3.0.0-alpha.7

### ISSUE THREAD

**Issue by JanStureNielsen** [DeviantJS/angular2-seed-material2#33]
Update the **Angular 2 Seed Material 2** project to Angular 2.0.0-rc.3 with the new 3.0.0-alpha.7 router.

**Comment by JanStureNielsen** [comment]
If no-one is working on this, I'll take it on...

**Comment by d3viant0ne** [comment]
Those updates come from the parent seed. I'll be picking up changes there when Material2 Alpha.6 drops this week.

**Comment by JanStureNielsen** [comment]
Yeah! 

  https://github.com/angular/material2/releases/tag/2.0.0-alpha.6

**Comment by d3viant0ne** [comment]
@JanStureNielsen   I'll pick up the latest from the parent seed, material2-alpha.6 & fix the e2e tests Friday night after I finish with my normal work deliverables.

**Comment by JanStureNielsen** [comment]
Thank you, @d3viant0ne!

**Comment by d3viant0ne** [comment]
@JanStureNielsen - I just rebased the latest changes in from the upstream seed with will temporarily  break #master.

Fixing that and pulling in Angular-Material2-alpha.6 in #34 

I'll have it all cleaned up this afternoon.

**Comment by d3viant0ne** [comment]
@JanStureNielsen - Now running on 
- @angular-2.0.0-rc.4
- @angular/router-3.0.0-alpha.8 
- @angular2-material-2.0.0-alpha.6

Test issues will be dealt with in #29

**Comment by JanStureNielsen** [comment]
`npm install; npm start` works -- thanks, Joshua!
