### ISSUE TITLE
warnings @angular2-material, after npm install, npm start error

### ISSUE THREAD

**Issue by jortegamo** [DeviantJS/angular2-seed-material2#41]
**IMPORTANT**: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here.

**Steps to reproduce and a minimal demo of the problem**

_What steps should we try in your demo to see the problem?_
git clone,
npm install
npm start
**Current behavior**
application shows loading... but not render the main component template

**Expected/desired behavior**
render the main component template

**Other information**

**Comment by JohnnyQQQQ** [comment]
Please post the console logs from your browser

**Comment by JohnnyQQQQ** [comment]
As the build is stable again I close this, if you have any further problems feel free to reopen the issue.
