### ISSUE TITLE
节点 1 上的项目“D:\Code\smartgitCode\angular2-seed-material2\node_modules\node- sass\b uild\binding.sln”(默认目标)。 ValidateSolutionConfiguration:   正在生成解决方案配置“Release|x64”。 MSBUILD : error MSB3428: 未能加载 Visual C++ 组件“VCBuild.exe”。要解决此问题， 1) 安装 .NET Fram ework 2.0 SDK；2) 安装 Microsoft Visual Studio 2005；或 3) 如果将该组件安装到了 其他位置，请将其位置添加到系统 路径中。 [D:\Code\smartgitCode\angular2-seed-material2\node_modules\node-sass\bu ild \binding.sln] 已完成生成项目“D:\Code\smartgitCode\angular2-seed-material2\node_modules\node-s ass\bui ld\binding.sln”(默认目标)的操作 - 失败。   生成失败。

### ISSUE THREAD

**Issue by clp334264003** [DeviantJS/angular2-seed-material2#57]
**IMPORTANT**: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here.

**Steps to reproduce and a minimal demo of the problem**

_What steps should we try in your demo to see the problem?_

**Current behavior**

**Expected/desired behavior**

**Other information**

**Comment by JohnnyQQQQ** [comment]
This is not enough information. Please follow the issue template.

**Comment by clp334264003** [comment]
gyp verb "Release" dir needed to be created? null
gyp verb copying "node.lib" for x64 C:\Users\Administrator\.node-gyp\5.10.0\Rele
ase\node.lib
gyp info spawn C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
生成启动时间为 2016/9/10 0:12:16。
节点 1 上的项目“D:\Code\smartgitCode\angular2-seed-material2\node_modules\node-
sass\b
uild\binding.sln”(默认目标)。
ValidateSolutionConfiguration:
  正在生成解决方案配置“Release|x64”。
libsass:
  C:\Program Files (x86)\Microsoft Visual Studio 9.0\Common7\IDE\..\..\vc\vcpac
  kages\VCBuild.exe D:\Code\smartgitCode\angular2-seed-material2\node_modules\n
  ode-sass\build\src\libsass.vcproj "Release|x64"
  错误: 项目文件“D:\Code\smartgitCode\angular2-seed-material2\node_modules\node
-sass\
  build\src\libsass.vcproj”找不到或者不是有效的项目文件。
  该项目的所有配置项都需要系统提供对某些平台的支持，但在此计算机上没有安装这些平
台。因此无法加载该项目。
MSBUILD : error MSB6006: "VCBuild.exe" exited with code -1. [D:\Code\smartgitCo
de\angular2-seed-material2\node_modules\node-sass\build\binding.sln]
已完成生成项目“D:\Code\smartgitCode\angular2-seed-material2\node_modules\node-s
ass\bui
ld\binding.sln”(默认目标)的操作 - 失败。


生成失败。

“D:\Code\smartgitCode\angular2-seed-material2\node_modules\node-sass\build\bind

ing.sln”(默认目标) (1) ->
(libsass 目标) ->
  MSBUILD : error MSB6006: "VCBuild.exe" exited with code -1. [D:\Code\smartgit
Code\angular2-seed-material2\node_modules\node-sass\build\binding.sln]

    0 个警告
    1 个错误

已用时间 00:00:00.74
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\Code\smartgitCode\angular2-seed-ma
terial2\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:204:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "E:\\software\\nodejs\\node.exe" "D:\\Code\\smartgitCode\\angul
ar2-seed-material2\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbo
se" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library
="
gyp ERR! cwd D:\Code\smartgitCode\angular2-seed-material2\node_modules\node-sass

gyp ERR! node -v v5.10.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
Build failed
postinstall:cross-spawn   / |##########################################-------|

**Comment by JohnnyQQQQ** [comment]
Please follow the issue template.
