### ISSUE TITLE
feature (material2 datatable)

### ISSUE THREAD

**Issue by allahbaksh** [DeviantJS/angular2-seed-material2#63]
**IMPORTANT**: Requires material2 datatable integration as showcased in https://github.com/DeviantJS/angular2-seed-material2/issues

**Comment by JohnnyQQQQ** [comment]
This is not a demo app. If you are looking for a demo app check out https://github.com/angular/material2/tree/master/src/demo-app or https://github.com/jelbourn/material2-app
