### ISSUE TITLE
hammer causing trouble on prod build

### ISSUE THREAD

**Issue by vip32** [DeviantJS/angular2-seed-material2#68]
something is wrong with the hammerjs dependency. this error comes when doing a 'run build.prod'

![image](https://cloud.githubusercontent.com/assets/164303/19121804/1a065e22-8b28-11e6-816e-997bf4641eea.png)

clearly that location is not right. the file is available as 'node_modules\hammerjs\hammer.js' < note that it is not named hammer**js**.js
dev builds (npm start) run fine

**Comment by Marcelh29** [comment]
In the config.js in the client folder, add hammerjs under types. Than the error will disappear. Other issue is that core.js of material cannot be found. You can fix that by adding 'core' to the material components in the SeedConfig . Now the prod build will succeed.

**Comment by JohnnyQQQQ** [comment]
Fixed #69

**Comment by vip32** [comment]
nice, prod build works now :)
